<?php

/**
 * @file
 * Module file for user_auth_token.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

define('AUTH_TOKEN_LENGTH', get_auth_token_length());

/**
 * Function to get auth_token_length.
 */
function get_auth_token_length() {
  $config = \Drupal::config('user_auth_token.settings');
  return $config->get('auth_token_length');
}

/**
 * Function to generate auth_token itself.
 */
function _generate_auth_token() {
  return substr(bin2hex(random_bytes(AUTH_TOKEN_LENGTH)), 0, AUTH_TOKEN_LENGTH);
}

/**
 * Implements hook_entity_presave().
 */
function user_auth_token_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'user' && $entity->bundle() == 'user') {

    // New token generated at entity creation moment.
    if ($entity->isNew() && !isset($entity->original)) {
      $entity->field_auth_token->setValue(_generate_auth_token());
    }

    // Token generated at entity creation moment should be preserved on entity update.
    if (!$entity->isNew() && isset($entity->original)) {
      if (isset($entity->original->field_auth_token->value)) {
        $entity->field_auth_token->setValue($entity->original->field_auth_token->value);
      }
      else {
        // Users exist, but no original value for field_auth_token.
        // Seems like module's first updb run.
      }
    }

    if (
      (!$entity->isNew() && !isset($entity->original))
    ||
      ( $entity->isNew() &&  isset($entity->original))
    ) {
      // We better brutally show this, as it's very unlikely to happen.
      die("Weird scenario here, ideally it shouldn't have happened.");
    }

  }
}

// EOF
